#!/bin/bash
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2003/03swap/socrates.n3 --query http://eulersharp.sourceforge.net/2003/03swap/socratesF.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2003/03swap/graph.axiom.n3 http://eulersharp.sourceforge.net/2003/03swap/rpo-rules.n3 --query http://eulersharp.sourceforge.net/2003/03swap/graph.filter.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2003/03swap/gedcom-facts.n3 http://eulersharp.sourceforge.net/2003/03swap/gedcom-relations.n3 http://eulersharp.sourceforge.net/2003/03swap/rpo-rules.n3 --query http://eulersharp.sourceforge.net/2003/03swap/gedcom-filter.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2004/04test/easterP.n3 --query http://eulersharp.sourceforge.net/2004/04test/easterF.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2004/04test/danP.n3 --query http://eulersharp.sourceforge.net/2004/04test/danC.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2003/03swap/lldmD.n3 http://eulersharp.sourceforge.net/2003/03swap/lldmP.n3 --query http://eulersharp.sourceforge.net/2003/03swap/lldmF.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2006/02swap/fcm-plugin.n3 http://eulersharp.sourceforge.net/2003/03swap/example001P.n3 http://eulersharp.sourceforge.net/2003/03swap/example002P.n3 http://eulersharp.sourceforge.net/2003/03swap/fl-rules.n3 --query http://eulersharp.sourceforge.net/2003/03swap/example003Q.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2004/04test/radlex.n3 --query http://eulersharp.sourceforge.net/2004/04test/radlexQ.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2004/04test/anatomy-facts.n3 http://eulersharp.sourceforge.net/2004/04test/anatomy-rules.n3 --query http://eulersharp.sourceforge.net/2004/04test/anatomy-filter.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2003/03swap/medic.n3 --query http://eulersharp.sourceforge.net/2003/03swap/medicF.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2004/04test/metastaticP001.n3 --query http://eulersharp.sourceforge.net/2004/04test/metastaticQ001.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://www.w3.org/2000/10/swap/test/reason/witch.n3 --query http://www.w3.org/2000/10/swap/test/reason/witch-goal.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2003/03swap/einstein.n3 --query http://eulersharp.sourceforge.net/2003/03swap/einsteinQ.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2004/04test/xanthippe.n3 --query http://eulersharp.sourceforge.net/2004/04test/xanthippeQ.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://www.w3.org/2000/10/swap/test/EricNeumann/exdata.n3 --query http://www.w3.org/2000/10/swap/test/EricNeumann/exquery.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://svn.code.sf.net/p/deductions/code/n3_new/test/dl-safe_small.owl.n3 http://svn.code.sf.net/p/deductions/code/n3_new/variableSubstitution.n3 http://svn.code.sf.net/p/deductions/code/n3_new/swrl-n3-rules.n3 --query http://svn.code.sf.net/p/deductions/code/n3_new/swrl-n3-rulesQ.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/biP.n3 --query http://eulersharp.sourceforge.net/2007/07test/biQ.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/rifP.n3 --query http://eulersharp.sourceforge.net/2007/07test/rifQ.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/age_instance.n3 http://eulersharp.sourceforge.net/2003/03swap/organism.n3 http://eulersharp.sourceforge.net/2003/03swap/human.n3 http://eulersharp.sourceforge.net/2003/03swap/event.n3 http://eulersharp.sourceforge.net/2003/03swap/rdfs-subClassOf.n3 http://eulersharp.sourceforge.net/2003/03swap/owl-intersectionOf.n3 http://eulersharp.sourceforge.net/2003/03swap/rdfs-subPropertyOf.n3 http://eulersharp.sourceforge.net/2003/03swap/owl-propertyChainAxiom.n3 http://eulersharp.sourceforge.net/2003/03swap/age_rules.n3 --query http://eulersharp.sourceforge.net/2007/07test/age_query.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/bmi_instances.n3 http://eulersharp.sourceforge.net/2003/03swap/bmi_rules.n3 http://eulersharp.sourceforge.net/2003/03swap/weightStatus_rules.n3 http://eulersharp.sourceforge.net/2003/03swap/age_rules_backward.n3 --query http://eulersharp.sourceforge.net/2007/07test/bmi_query.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2009/12dtb/test-facts.n3 http://eulersharp.sourceforge.net/2009/12dtb/test-relations-1000.n3 --query http://eulersharp.sourceforge.net/2009/12dtb/test-query.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/utf8.n3 --pass
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://notes.restdesc.org/2011/images/agent_image.n3 http://notes.restdesc.org/2011/images/description_images.n3 --pass
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://notes.restdesc.org/2011/images/server_image.n3 http://notes.restdesc.org/2011/images/description_thumbnail.n3 --pass
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" --quick-answer http://notes.restdesc.org/2011/images/agent_image.n3 http://notes.restdesc.org/2011/images/description_images.n3 http://notes.restdesc.org/2011/images/description_thumbnail.n3 --query http://notes.restdesc.org/2011/images/agent_goal.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" --quick-answer http://eulersharp.sourceforge.net/2007/07test/fib.n3 --query http://eulersharp.sourceforge.net/2007/07test/fibQ.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/tak.n3 --query http://eulersharp.sourceforge.net/2007/07test/takQ.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/hanoi.n3 --pass
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/cyclic-rules.n3 --pass
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/parteval.n3 --query http://eulersharp.sourceforge.net/2007/07test/parteval_query.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/initial.n3 http://eulersharp.sourceforge.net/2007/07test/path-256-3.n3 --query http://eulersharp.sourceforge.net/2007/07test/goal.n3
echo EYE entailment test case $(($LINENO-1)) $(date) >&2; eye "$@" http://eulersharp.sourceforge.net/2007/07test/turing.n3 --query http://eulersharp.sourceforge.net/2007/07test/turingQ.n3
