#!/bin/bash
eye "$@" http://eulersharp.sourceforge.net/2003/03swap/socrates.n3 --query http://eulersharp.sourceforge.net/2003/03swap/socratesF.n3
eye "$@" http://eulersharp.sourceforge.net/2003/03swap/graph.axiom.n3 http://eulersharp.sourceforge.net/2003/03swap/rpo-rules.n3 --query http://eulersharp.sourceforge.net/2003/03swap/graph.filter.n3
eye "$@" http://eulersharp.sourceforge.net/2003/03swap/gedcom-facts.n3 http://eulersharp.sourceforge.net/2003/03swap/gedcom-relations.n3 http://eulersharp.sourceforge.net/2003/03swap/rpo-rules.n3 --query http://eulersharp.sourceforge.net/2003/03swap/gedcom-filter.n3
eye "$@" http://eulersharp.sourceforge.net/2004/04test/easterP.n3 --query http://eulersharp.sourceforge.net/2004/04test/easterF.n3
eye "$@" http://eulersharp.sourceforge.net/2004/04test/danP.n3 --query http://eulersharp.sourceforge.net/2004/04test/danC.n3
eye "$@" http://eulersharp.sourceforge.net/2003/03swap/lldmD.n3 http://eulersharp.sourceforge.net/2003/03swap/lldmP.n3 --query http://eulersharp.sourceforge.net/2003/03swap/lldmF.n3
eye "$@" --plugin http://eulersharp.sourceforge.net/2006/02swap/fcm-plugin.yap http://eulersharp.sourceforge.net/2003/03swap/example001P.n3 http://eulersharp.sourceforge.net/2003/03swap/example002P.n3 http://eulersharp.sourceforge.net/2003/03swap/fl-rules.n3 --query http://eulersharp.sourceforge.net/2003/03swap/example003Q.n3
eye "$@" http://eulersharp.sourceforge.net/2004/04test/radlex.n3 --query http://eulersharp.sourceforge.net/2004/04test/radlexQ.n3
eye "$@" http://eulersharp.sourceforge.net/2004/04test/anatomy-facts.n3 http://eulersharp.sourceforge.net/2004/04test/anatomy-rules.n3 --query http://eulersharp.sourceforge.net/2004/04test/anatomy-filter.n3
eye "$@" http://eulersharp.sourceforge.net/2003/03swap/medic.n3 --query http://eulersharp.sourceforge.net/2003/03swap/medicF.n3
eye "$@" http://eulersharp.sourceforge.net/2004/04test/metastaticP001.n3 --query http://eulersharp.sourceforge.net/2004/04test/metastaticQ001.n3
eye "$@" http://www.w3.org/2000/10/swap/test/reason/witch.n3 --query http://www.w3.org/2000/10/swap/test/reason/witch-goal.n3
eye "$@" http://eulersharp.sourceforge.net/2003/03swap/einstein.n3 --query http://eulersharp.sourceforge.net/2003/03swap/einsteinQ.n3
eye "$@" http://eulersharp.sourceforge.net/2004/04test/xanthippe.n3 --query http://eulersharp.sourceforge.net/2004/04test/xanthippeQ.n3
eye "$@" http://eulersharp.sourceforge.net/2003/03swap/lf.n3 --query http://eulersharp.sourceforge.net/2003/03swap/lfF.n3
eye "$@" http://www.w3.org/2000/10/swap/test/EricNeumann/exdata.n3 --query http://eulersharp.sourceforge.net/2004/04test/exonQ.n3
eye "$@" http://deductions.svn.sourceforge.net/svnroot/deductions/n3_new/test/dl-safe_small.owl.n3 http://deductions.svn.sourceforge.net/svnroot/deductions/n3_new/variableSubstitution.n3 http://deductions.svn.sourceforge.net/svnroot/deductions/n3_new/swrl-n3-rules.n3 --query http://deductions.svn.sourceforge.net/svnroot/deductions/n3_new/swrl-n3-rulesQ.n3
